package(default_visibility = ["//skylb:__subpackages__"])

load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "static",
    deps = [
        "//skylb/dashboard/static/images",
        "//skylb/dashboard/static/scripts",
        "//skylb/dashboard/static/styles",
    ],
)
