# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'skylb'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    metrics_path: '/metrics'

    static_configs:
      - targets: [
        '192.168.221.104:11920',
        '192.168.221.105:11920',
        '192.168.221.106:11920',
      ]

  - job_name: 'skytest-client-go'

    metrics_path: '/_/metrics'

    static_configs:
      - targets: [
        '192.168.221.101:18005',
        '192.168.221.102:18005',
        '192.168.221.103:18005',
        '192.168.221.107:18005',
        '192.168.221.108:18005',
        '192.168.221.109:18005',
      ]

  - job_name: 'skytest-client-java'

    metrics_path: '/_/metrics'

    static_configs:
      - targets: [
        '192.168.221.101:11950',
        '192.168.221.102:11950',
        '192.168.221.103:11950',
        '192.168.221.107:11950',
        '192.168.221.108:11950',
        '192.168.221.109:11950',
      ]

  - job_name: 'skytest-client-java-old'

    metrics_path: '/_/metrics'

    static_configs:
      - targets: [
        '192.168.221.101:12950',
        '192.168.221.102:12950',
        '192.168.221.103:12950',
        '192.168.221.107:12950',
        '192.168.221.108:12950',
        '192.168.221.109:12950',
      ]

  - job_name: 'skytest-server'

    metrics_path: '/_/metrics'

    static_configs:
      - targets: [
        '192.168.221.104:18001',
        '192.168.221.105:18001',
        '192.168.221.106:18001',
      ]

  - job_name: 'skylbweb'

    metrics_path: '/_/metrics'

    static_configs:
      - targets: [
        '192.168.221.106:18092',
      ]

